FROM python:3.11-slim
WORKDIR /app
COPY ingestion/consumer.requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY ingestion /app/ingestion
CMD ["python", "/app/ingestion/consumer_to_minio.py"]
