# ingestion/producer_cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: spotify-producer
  namespace: bigdata
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid   # NGĂN CHẠY MỚI NẾU CŨ CHƯA XONG
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: producer
            image: duongnguyen2204/spotify-producer:latest
            env:
            - name: SPOTIFY_CLIENT_ID
              value: "ad3f7ef1be534e21aa3356fa126bf52f"
            - name: SPOTIFY_CLIENT_SECRET
              value: "7de231f55f4a4532bedfc2e5ce4c9334"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "spotify_tracks"
          restartPolicy: Never   # CHẠY XONG LÀ CHẾT